application: teamcitymonitor
version: 9
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /images
  static_dir: images

- url: /styles
  static_dir: styles

- url: /.*
  script: main.app

libraries:
  - name: django
    version: "1.4"
